name: xgboost-mnist-from-for-fsx
spec:	
    instancecount: 1
    instancetype: ml.m4.xlarge
    volumesize: 5
    maxruntimeinseconds: 86400
    rolearn: arn:aws:iam::123456789012:role/service-role/AmazonSageMaker-ExecutionRole
    region: us-west-2
    image: 433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:1
    traininginputmode: File
    hyperparameters:
       max_depth: 5
       eta: 0.2
       num_round: 10
       gamma: 4
       min_child_weight: 6
       silent: 0
       objective: multi:softmax
       num_class: 10
       num_round: 10
    outputpath: s3://my-bucket/xgboost/
    inputdataconfig:
      - channel: train 
        filesystem: 
            filesystemtype: FSxLustre
            filesystemid: fs-0d0f8e3f721664c98
            directorypath: /fsx/sagemaker/xgboost-mnist
      - channel: validation
        filesystem: 
            filesystemtype: FSxLustre
            filesystemid: fs-0d0f8e3f721664c98
            directorypath: /fsx/sagemaker/xgboost-mnist
    vpcconfig:
        securitygroupids: 
          - sg-4b23c421
        subnets: 
          - subnet-ae0a65c6
          - subnet-2af0fa67
          - subnet-dddb7fa7

