name: xgboost-mnist-from-for-spot
spec:	
  instanceCount: 1
  instanceType: ml.m4.xlarge
  volumeSizeInGB: 5
  maxRuntimeInSeconds: 86400
  roleArn: arn:aws:iam::123456789012:role/service-role/AmazonSageMaker-ExecutionRole
  region: us-west-2
  image: 433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:1
  trainingInputMode: File
  hyperparameters:
    max_depth: 5
    eta: 0.2
    num_round: 10
    gamma: 4
    min_child_weight: 6
    silent: 0
    objective: multi:softmax
    num_class: 10
    num_round: 10
  inputDataConfig:
    - channel: train 
      s3: 
        s3Uri: s3://my-bucket/train/
    - channel: validation
      s3: 
        s3Uri: s3://my-bucket/validation/
  outputPath: s3://my-bucket/xgboost/
  enableManagedSpotTraining: true
  stoppingCondition:
    maxRuntime: 3599
    maxWaitTime: 3600
  checkpointConfig:
    s3Uri: s3://my-bucket/checkpoints/
