apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: PLACEHOLDER-NAMESPACE
namePrefix: sagemaker-k8s-operator-
  
bases:
- ../../../base
- resources

patchesStrategicMerge:
- resources/manager_add_service_account_patch.yaml
- resources/modify_cluster_roles_to_roles.yaml

# Patch all ClusterRole* to Role* kinds
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: proxy-role
  patch: |-
    - op: replace
      path: "/kind"
      value: Role
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: manager-rolebinding
  patch: |-
    - op: replace
      path: "/kind"
      value: RoleBinding
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: proxy-rolebinding
  patch: |-
    - op: replace
      path: "/kind"
      value: RoleBinding
# Add --namespace option to the manager pod
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: system
    name: controller-manager
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/1/args/-"
      value: --namespace=PLACEHOLDER-NAMESPACE