// +build !ignore_autogenerated

/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// autogenerated by controller-gen object, do not modify manually

package v1

import (
	common "github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/common"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperparameterTuningJob) DeepCopyInto(out *HyperparameterTuningJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperparameterTuningJob.
func (in *HyperparameterTuningJob) DeepCopy() *HyperparameterTuningJob {
	if in == nil {
		return nil
	}
	out := new(HyperparameterTuningJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperparameterTuningJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperparameterTuningJobList) DeepCopyInto(out *HyperparameterTuningJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HyperparameterTuningJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperparameterTuningJobList.
func (in *HyperparameterTuningJobList) DeepCopy() *HyperparameterTuningJobList {
	if in == nil {
		return nil
	}
	out := new(HyperparameterTuningJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperparameterTuningJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperparameterTuningJobSpec) DeepCopyInto(out *HyperparameterTuningJobSpec) {
	*out = *in
	if in.HyperParameterTuningJobConfig != nil {
		in, out := &in.HyperParameterTuningJobConfig, &out.HyperParameterTuningJobConfig
		*out = new(common.HyperParameterTuningJobConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HyperParameterTuningJobName != nil {
		in, out := &in.HyperParameterTuningJobName, &out.HyperParameterTuningJobName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]common.Tag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrainingJobDefinition != nil {
		in, out := &in.TrainingJobDefinition, &out.TrainingJobDefinition
		*out = new(common.HyperParameterTrainingJobDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.WarmStartConfig != nil {
		in, out := &in.WarmStartConfig, &out.WarmStartConfig
		*out = new(common.HyperParameterTuningJobWarmStartConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SageMakerEndpoint != nil {
		in, out := &in.SageMakerEndpoint, &out.SageMakerEndpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperparameterTuningJobSpec.
func (in *HyperparameterTuningJobSpec) DeepCopy() *HyperparameterTuningJobSpec {
	if in == nil {
		return nil
	}
	out := new(HyperparameterTuningJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperparameterTuningJobStatus) DeepCopyInto(out *HyperparameterTuningJobStatus) {
	*out = *in
	if in.BestTrainingJob != nil {
		in, out := &in.BestTrainingJob, &out.BestTrainingJob
		*out = new(common.HyperParameterTrainingJobSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = new(metav1.Time)
		(*in).DeepCopyInto(*out)
	}
	if in.TrainingJobStatusCounters != nil {
		in, out := &in.TrainingJobStatusCounters, &out.TrainingJobStatusCounters
		*out = new(common.TrainingJobStatusCounters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperparameterTuningJobStatus.
func (in *HyperparameterTuningJobStatus) DeepCopy() *HyperparameterTuningJobStatus {
	if in == nil {
		return nil
	}
	out := new(HyperparameterTuningJobStatus)
	in.DeepCopyInto(out)
	return out
}
