/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	batchtransformjob "github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/batchtransformjob"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BatchTransformJobLister helps list BatchTransformJobs.
type BatchTransformJobLister interface {
	// List lists all BatchTransformJobs in the indexer.
	List(selector labels.Selector) (ret []*batchtransformjob.BatchTransformJob, err error)
	// BatchTransformJobs returns an object that can list and get BatchTransformJobs.
	BatchTransformJobs(namespace string) BatchTransformJobNamespaceLister
	BatchTransformJobListerExpansion
}

// batchTransformJobLister implements the BatchTransformJobLister interface.
type batchTransformJobLister struct {
	indexer cache.Indexer
}

// NewBatchTransformJobLister returns a new BatchTransformJobLister.
func NewBatchTransformJobLister(indexer cache.Indexer) BatchTransformJobLister {
	return &batchTransformJobLister{indexer: indexer}
}

// List lists all BatchTransformJobs in the indexer.
func (s *batchTransformJobLister) List(selector labels.Selector) (ret []*batchtransformjob.BatchTransformJob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*batchtransformjob.BatchTransformJob))
	})
	return ret, err
}

// BatchTransformJobs returns an object that can list and get BatchTransformJobs.
func (s *batchTransformJobLister) BatchTransformJobs(namespace string) BatchTransformJobNamespaceLister {
	return batchTransformJobNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BatchTransformJobNamespaceLister helps list and get BatchTransformJobs.
type BatchTransformJobNamespaceLister interface {
	// List lists all BatchTransformJobs in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*batchtransformjob.BatchTransformJob, err error)
	// Get retrieves the BatchTransformJob from the indexer for a given namespace and name.
	Get(name string) (*batchtransformjob.BatchTransformJob, error)
	BatchTransformJobNamespaceListerExpansion
}

// batchTransformJobNamespaceLister implements the BatchTransformJobNamespaceLister
// interface.
type batchTransformJobNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BatchTransformJobs in the indexer for a given namespace.
func (s batchTransformJobNamespaceLister) List(selector labels.Selector) (ret []*batchtransformjob.BatchTransformJob, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*batchtransformjob.BatchTransformJob))
	})
	return ret, err
}

// Get retrieves the BatchTransformJob from the indexer for a given namespace and name.
func (s batchTransformJobNamespaceLister) Get(name string) (*batchtransformjob.BatchTransformJob, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(batchtransformjob.Resource("batchtransformjob"), name)
	}
	return obj.(*batchtransformjob.BatchTransformJob), nil
}
