/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package hyperparametertuningjob

import (
	"context"
	"time"

	hyperparametertuningjob "github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/hyperparametertuningjob"
	scheme "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HyperparameterTuningJobsGetter has a method to return a HyperparameterTuningJobInterface.
// A group's client should implement this interface.
type HyperparameterTuningJobsGetter interface {
	HyperparameterTuningJobs(namespace string) HyperparameterTuningJobInterface
}

// HyperparameterTuningJobInterface has methods to work with HyperparameterTuningJob resources.
type HyperparameterTuningJobInterface interface {
	Create(ctx context.Context, hyperparameterTuningJob *hyperparametertuningjob.HyperparameterTuningJob, opts v1.CreateOptions) (*hyperparametertuningjob.HyperparameterTuningJob, error)
	Update(ctx context.Context, hyperparameterTuningJob *hyperparametertuningjob.HyperparameterTuningJob, opts v1.UpdateOptions) (*hyperparametertuningjob.HyperparameterTuningJob, error)
	UpdateStatus(ctx context.Context, hyperparameterTuningJob *hyperparametertuningjob.HyperparameterTuningJob, opts v1.UpdateOptions) (*hyperparametertuningjob.HyperparameterTuningJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*hyperparametertuningjob.HyperparameterTuningJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*hyperparametertuningjob.HyperparameterTuningJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hyperparametertuningjob.HyperparameterTuningJob, err error)
	HyperparameterTuningJobExpansion
}

// hyperparameterTuningJobs implements HyperparameterTuningJobInterface
type hyperparameterTuningJobs struct {
	client rest.Interface
	ns     string
}

// newHyperparameterTuningJobs returns a HyperparameterTuningJobs
func newHyperparameterTuningJobs(c *V1HyperparametertuningjobClient, namespace string) *hyperparameterTuningJobs {
	return &hyperparameterTuningJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hyperparameterTuningJob, and returns the corresponding hyperparameterTuningJob object, and an error if there is any.
func (c *hyperparameterTuningJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *hyperparametertuningjob.HyperparameterTuningJob, err error) {
	result = &hyperparametertuningjob.HyperparameterTuningJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HyperparameterTuningJobs that match those selectors.
func (c *hyperparameterTuningJobs) List(ctx context.Context, opts v1.ListOptions) (result *hyperparametertuningjob.HyperparameterTuningJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &hyperparametertuningjob.HyperparameterTuningJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hyperparameterTuningJobs.
func (c *hyperparameterTuningJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a hyperparameterTuningJob and creates it.  Returns the server's representation of the hyperparameterTuningJob, and an error, if there is any.
func (c *hyperparameterTuningJobs) Create(ctx context.Context, hyperparameterTuningJob *hyperparametertuningjob.HyperparameterTuningJob, opts v1.CreateOptions) (result *hyperparametertuningjob.HyperparameterTuningJob, err error) {
	result = &hyperparametertuningjob.HyperparameterTuningJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hyperparameterTuningJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a hyperparameterTuningJob and updates it. Returns the server's representation of the hyperparameterTuningJob, and an error, if there is any.
func (c *hyperparameterTuningJobs) Update(ctx context.Context, hyperparameterTuningJob *hyperparametertuningjob.HyperparameterTuningJob, opts v1.UpdateOptions) (result *hyperparametertuningjob.HyperparameterTuningJob, err error) {
	result = &hyperparametertuningjob.HyperparameterTuningJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		Name(hyperparameterTuningJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hyperparameterTuningJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *hyperparameterTuningJobs) UpdateStatus(ctx context.Context, hyperparameterTuningJob *hyperparametertuningjob.HyperparameterTuningJob, opts v1.UpdateOptions) (result *hyperparametertuningjob.HyperparameterTuningJob, err error) {
	result = &hyperparametertuningjob.HyperparameterTuningJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		Name(hyperparameterTuningJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hyperparameterTuningJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the hyperparameterTuningJob and deletes it. Returns an error if one occurs.
func (c *hyperparameterTuningJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hyperparameterTuningJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched hyperparameterTuningJob.
func (c *hyperparameterTuningJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hyperparametertuningjob.HyperparameterTuningJob, err error) {
	result = &hyperparametertuningjob.HyperparameterTuningJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
