/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	hostingdeploymentv1 "github.com/aws/amazon-sagemaker-operator-for-k8s/api/hostingdeployment/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHostingDeployments implements HostingDeploymentInterface
type FakeHostingDeployments struct {
	Fake *FakeHostingdeploymentV1
	ns   string
}

var hostingdeploymentsResource = schema.GroupVersionResource{Group: "hostingdeployment", Version: "v1", Resource: "hostingdeployments"}

var hostingdeploymentsKind = schema.GroupVersionKind{Group: "hostingdeployment", Version: "v1", Kind: "HostingDeployment"}

// Get takes name of the hostingDeployment, and returns the corresponding hostingDeployment object, and an error if there is any.
func (c *FakeHostingDeployments) Get(name string, options v1.GetOptions) (result *hostingdeploymentv1.HostingDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hostingdeploymentsResource, c.ns, name), &hostingdeploymentv1.HostingDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hostingdeploymentv1.HostingDeployment), err
}

// List takes label and field selectors, and returns the list of HostingDeployments that match those selectors.
func (c *FakeHostingDeployments) List(opts v1.ListOptions) (result *hostingdeploymentv1.HostingDeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hostingdeploymentsResource, hostingdeploymentsKind, c.ns, opts), &hostingdeploymentv1.HostingDeploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hostingdeploymentv1.HostingDeploymentList{ListMeta: obj.(*hostingdeploymentv1.HostingDeploymentList).ListMeta}
	for _, item := range obj.(*hostingdeploymentv1.HostingDeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hostingDeployments.
func (c *FakeHostingDeployments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hostingdeploymentsResource, c.ns, opts))

}

// Create takes the representation of a hostingDeployment and creates it.  Returns the server's representation of the hostingDeployment, and an error, if there is any.
func (c *FakeHostingDeployments) Create(hostingDeployment *hostingdeploymentv1.HostingDeployment) (result *hostingdeploymentv1.HostingDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hostingdeploymentsResource, c.ns, hostingDeployment), &hostingdeploymentv1.HostingDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hostingdeploymentv1.HostingDeployment), err
}

// Update takes the representation of a hostingDeployment and updates it. Returns the server's representation of the hostingDeployment, and an error, if there is any.
func (c *FakeHostingDeployments) Update(hostingDeployment *hostingdeploymentv1.HostingDeployment) (result *hostingdeploymentv1.HostingDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hostingdeploymentsResource, c.ns, hostingDeployment), &hostingdeploymentv1.HostingDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hostingdeploymentv1.HostingDeployment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHostingDeployments) UpdateStatus(hostingDeployment *hostingdeploymentv1.HostingDeployment) (*hostingdeploymentv1.HostingDeployment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hostingdeploymentsResource, "status", c.ns, hostingDeployment), &hostingdeploymentv1.HostingDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hostingdeploymentv1.HostingDeployment), err
}

// Delete takes name of the hostingDeployment and deletes it. Returns an error if one occurs.
func (c *FakeHostingDeployments) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hostingdeploymentsResource, c.ns, name), &hostingdeploymentv1.HostingDeployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHostingDeployments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hostingdeploymentsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &hostingdeploymentv1.HostingDeploymentList{})
	return err
}

// Patch applies the patch and returns the patched hostingDeployment.
func (c *FakeHostingDeployments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hostingdeploymentv1.HostingDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hostingdeploymentsResource, c.ns, name, pt, data, subresources...), &hostingdeploymentv1.HostingDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hostingdeploymentv1.HostingDeployment), err
}
