apiVersion: v1
kind: ServiceAccount
metadata: 
  name: default
  namespace: sagemaker-k8s-operator-system
  # Until we find how to add this using kustomize
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/DELETE_ME
