apiVersion: v1
name: amazon-sagemaker-operator-for-k8s-install-crds
version: 1.0.0
appVersion: 1.2.1
description: A Helm chart for deploying the Amazon SageMaker Operator CRDs for Kubernetes using EKS IAM roles for service accounts.
maintainers:
  - name: Gautam Kumar
    email: gauta@amazon.com
  - name: Suraj Kota
    email: surakota@amazon.com
  - name: Kartik Kalamadi
    email: kalamadi@amazon.com
  - name: Meghna Baijal
    email: mbaijal@amazon.com
keywords:
  - amazon
  - aws
  - sagemaker
  - eks
