/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package batchtransformjob

import (
	"time"

	batchtransformjob "github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/batchtransformjob"
	scheme "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BatchTransformJobsGetter has a method to return a BatchTransformJobInterface.
// A group's client should implement this interface.
type BatchTransformJobsGetter interface {
	BatchTransformJobs(namespace string) BatchTransformJobInterface
}

// BatchTransformJobInterface has methods to work with BatchTransformJob resources.
type BatchTransformJobInterface interface {
	Create(*batchtransformjob.BatchTransformJob) (*batchtransformjob.BatchTransformJob, error)
	Update(*batchtransformjob.BatchTransformJob) (*batchtransformjob.BatchTransformJob, error)
	UpdateStatus(*batchtransformjob.BatchTransformJob) (*batchtransformjob.BatchTransformJob, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*batchtransformjob.BatchTransformJob, error)
	List(opts v1.ListOptions) (*batchtransformjob.BatchTransformJobList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *batchtransformjob.BatchTransformJob, err error)
	BatchTransformJobExpansion
}

// batchTransformJobs implements BatchTransformJobInterface
type batchTransformJobs struct {
	client rest.Interface
	ns     string
}

// newBatchTransformJobs returns a BatchTransformJobs
func newBatchTransformJobs(c *V1BatchtransformjobClient, namespace string) *batchTransformJobs {
	return &batchTransformJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the batchTransformJob, and returns the corresponding batchTransformJob object, and an error if there is any.
func (c *batchTransformJobs) Get(name string, options v1.GetOptions) (result *batchtransformjob.BatchTransformJob, err error) {
	result = &batchtransformjob.BatchTransformJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BatchTransformJobs that match those selectors.
func (c *batchTransformJobs) List(opts v1.ListOptions) (result *batchtransformjob.BatchTransformJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &batchtransformjob.BatchTransformJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested batchTransformJobs.
func (c *batchTransformJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a batchTransformJob and creates it.  Returns the server's representation of the batchTransformJob, and an error, if there is any.
func (c *batchTransformJobs) Create(batchTransformJob *batchtransformjob.BatchTransformJob) (result *batchtransformjob.BatchTransformJob, err error) {
	result = &batchtransformjob.BatchTransformJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		Body(batchTransformJob).
		Do().
		Into(result)
	return
}

// Update takes the representation of a batchTransformJob and updates it. Returns the server's representation of the batchTransformJob, and an error, if there is any.
func (c *batchTransformJobs) Update(batchTransformJob *batchtransformjob.BatchTransformJob) (result *batchtransformjob.BatchTransformJob, err error) {
	result = &batchtransformjob.BatchTransformJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		Name(batchTransformJob.Name).
		Body(batchTransformJob).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *batchTransformJobs) UpdateStatus(batchTransformJob *batchtransformjob.BatchTransformJob) (result *batchtransformjob.BatchTransformJob, err error) {
	result = &batchtransformjob.BatchTransformJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		Name(batchTransformJob.Name).
		SubResource("status").
		Body(batchTransformJob).
		Do().
		Into(result)
	return
}

// Delete takes name of the batchTransformJob and deletes it. Returns an error if one occurs.
func (c *batchTransformJobs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *batchTransformJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched batchTransformJob.
func (c *batchTransformJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *batchtransformjob.BatchTransformJob, err error) {
	result = &batchtransformjob.BatchTransformJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("batchtransformjobs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
