/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package batchtransformjob

import (
	"context"
	"time"

	batchtransformjob "github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/batchtransformjob"
	scheme "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BatchTransformJobsGetter has a method to return a BatchTransformJobInterface.
// A group's client should implement this interface.
type BatchTransformJobsGetter interface {
	BatchTransformJobs(namespace string) BatchTransformJobInterface
}

// BatchTransformJobInterface has methods to work with BatchTransformJob resources.
type BatchTransformJobInterface interface {
	Create(ctx context.Context, batchTransformJob *batchtransformjob.BatchTransformJob, opts v1.CreateOptions) (*batchtransformjob.BatchTransformJob, error)
	Update(ctx context.Context, batchTransformJob *batchtransformjob.BatchTransformJob, opts v1.UpdateOptions) (*batchtransformjob.BatchTransformJob, error)
	UpdateStatus(ctx context.Context, batchTransformJob *batchtransformjob.BatchTransformJob, opts v1.UpdateOptions) (*batchtransformjob.BatchTransformJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*batchtransformjob.BatchTransformJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*batchtransformjob.BatchTransformJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *batchtransformjob.BatchTransformJob, err error)
	BatchTransformJobExpansion
}

// batchTransformJobs implements BatchTransformJobInterface
type batchTransformJobs struct {
	client rest.Interface
	ns     string
}

// newBatchTransformJobs returns a BatchTransformJobs
func newBatchTransformJobs(c *V1BatchtransformjobClient, namespace string) *batchTransformJobs {
	return &batchTransformJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the batchTransformJob, and returns the corresponding batchTransformJob object, and an error if there is any.
func (c *batchTransformJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *batchtransformjob.BatchTransformJob, err error) {
	result = &batchtransformjob.BatchTransformJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BatchTransformJobs that match those selectors.
func (c *batchTransformJobs) List(ctx context.Context, opts v1.ListOptions) (result *batchtransformjob.BatchTransformJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &batchtransformjob.BatchTransformJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested batchTransformJobs.
func (c *batchTransformJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a batchTransformJob and creates it.  Returns the server's representation of the batchTransformJob, and an error, if there is any.
func (c *batchTransformJobs) Create(ctx context.Context, batchTransformJob *batchtransformjob.BatchTransformJob, opts v1.CreateOptions) (result *batchtransformjob.BatchTransformJob, err error) {
	result = &batchtransformjob.BatchTransformJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(batchTransformJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a batchTransformJob and updates it. Returns the server's representation of the batchTransformJob, and an error, if there is any.
func (c *batchTransformJobs) Update(ctx context.Context, batchTransformJob *batchtransformjob.BatchTransformJob, opts v1.UpdateOptions) (result *batchtransformjob.BatchTransformJob, err error) {
	result = &batchtransformjob.BatchTransformJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		Name(batchTransformJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(batchTransformJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *batchTransformJobs) UpdateStatus(ctx context.Context, batchTransformJob *batchtransformjob.BatchTransformJob, opts v1.UpdateOptions) (result *batchtransformjob.BatchTransformJob, err error) {
	result = &batchtransformjob.BatchTransformJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		Name(batchTransformJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(batchTransformJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the batchTransformJob and deletes it. Returns an error if one occurs.
func (c *batchTransformJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *batchTransformJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("batchtransformjobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched batchTransformJob.
func (c *batchTransformJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *batchtransformjob.BatchTransformJob, err error) {
	result = &batchtransformjob.BatchTransformJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("batchtransformjobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
