/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	endpointconfig "github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/endpointconfig"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEndpointConfigs implements EndpointConfigInterface
type FakeEndpointConfigs struct {
	Fake *FakeV1Endpointconfig
	ns   string
}

var endpointconfigsResource = schema.GroupVersionResource{Group: "v1", Version: "endpointconfig", Resource: "endpointconfigs"}

var endpointconfigsKind = schema.GroupVersionKind{Group: "v1", Version: "endpointconfig", Kind: "EndpointConfig"}

// Get takes name of the endpointConfig, and returns the corresponding endpointConfig object, and an error if there is any.
func (c *FakeEndpointConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *endpointconfig.EndpointConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(endpointconfigsResource, c.ns, name), &endpointconfig.EndpointConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*endpointconfig.EndpointConfig), err
}

// List takes label and field selectors, and returns the list of EndpointConfigs that match those selectors.
func (c *FakeEndpointConfigs) List(ctx context.Context, opts v1.ListOptions) (result *endpointconfig.EndpointConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(endpointconfigsResource, endpointconfigsKind, c.ns, opts), &endpointconfig.EndpointConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &endpointconfig.EndpointConfigList{ListMeta: obj.(*endpointconfig.EndpointConfigList).ListMeta}
	for _, item := range obj.(*endpointconfig.EndpointConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested endpointConfigs.
func (c *FakeEndpointConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(endpointconfigsResource, c.ns, opts))

}

// Create takes the representation of a endpointConfig and creates it.  Returns the server's representation of the endpointConfig, and an error, if there is any.
func (c *FakeEndpointConfigs) Create(ctx context.Context, endpointConfig *endpointconfig.EndpointConfig, opts v1.CreateOptions) (result *endpointconfig.EndpointConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(endpointconfigsResource, c.ns, endpointConfig), &endpointconfig.EndpointConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*endpointconfig.EndpointConfig), err
}

// Update takes the representation of a endpointConfig and updates it. Returns the server's representation of the endpointConfig, and an error, if there is any.
func (c *FakeEndpointConfigs) Update(ctx context.Context, endpointConfig *endpointconfig.EndpointConfig, opts v1.UpdateOptions) (result *endpointconfig.EndpointConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(endpointconfigsResource, c.ns, endpointConfig), &endpointconfig.EndpointConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*endpointconfig.EndpointConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEndpointConfigs) UpdateStatus(ctx context.Context, endpointConfig *endpointconfig.EndpointConfig, opts v1.UpdateOptions) (*endpointconfig.EndpointConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(endpointconfigsResource, "status", c.ns, endpointConfig), &endpointconfig.EndpointConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*endpointconfig.EndpointConfig), err
}

// Delete takes name of the endpointConfig and deletes it. Returns an error if one occurs.
func (c *FakeEndpointConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(endpointconfigsResource, c.ns, name), &endpointconfig.EndpointConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEndpointConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(endpointconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &endpointconfig.EndpointConfigList{})
	return err
}

// Patch applies the patch and returns the patched endpointConfig.
func (c *FakeEndpointConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *endpointconfig.EndpointConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(endpointconfigsResource, c.ns, name, pt, data, subresources...), &endpointconfig.EndpointConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*endpointconfig.EndpointConfig), err
}
