/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned"
	v1batchtransformjob "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/batchtransformjob"
	fakev1batchtransformjob "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/batchtransformjob/fake"
	v1endpointconfig "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/endpointconfig"
	fakev1endpointconfig "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/endpointconfig/fake"
	v1hostingdeployment "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/hostingdeployment"
	fakev1hostingdeployment "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/hostingdeployment/fake"
	v1hyperparametertuningjob "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/hyperparametertuningjob"
	fakev1hyperparametertuningjob "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/hyperparametertuningjob/fake"
	v1model "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/model"
	fakev1model "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/model/fake"
	v1trainingjob "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/trainingjob"
	fakev1trainingjob "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/trainingjob/fake"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var _ clientset.Interface = &Clientset{}

// V1Trainingjob retrieves the V1TrainingjobClient
func (c *Clientset) V1Trainingjob() v1trainingjob.V1TrainingjobInterface {
	return &fakev1trainingjob.FakeV1Trainingjob{Fake: &c.Fake}
}

// V1Batchtransformjob retrieves the V1BatchtransformjobClient
func (c *Clientset) V1Batchtransformjob() v1batchtransformjob.V1BatchtransformjobInterface {
	return &fakev1batchtransformjob.FakeV1Batchtransformjob{Fake: &c.Fake}
}

// V1Endpointconfig retrieves the V1EndpointconfigClient
func (c *Clientset) V1Endpointconfig() v1endpointconfig.V1EndpointconfigInterface {
	return &fakev1endpointconfig.FakeV1Endpointconfig{Fake: &c.Fake}
}

// V1Hostingdeployment retrieves the V1HostingdeploymentClient
func (c *Clientset) V1Hostingdeployment() v1hostingdeployment.V1HostingdeploymentInterface {
	return &fakev1hostingdeployment.FakeV1Hostingdeployment{Fake: &c.Fake}
}

// V1Hyperparametertuningjob retrieves the V1HyperparametertuningjobClient
func (c *Clientset) V1Hyperparametertuningjob() v1hyperparametertuningjob.V1HyperparametertuningjobInterface {
	return &fakev1hyperparametertuningjob.FakeV1Hyperparametertuningjob{Fake: &c.Fake}
}

// V1Model retrieves the V1ModelClient
func (c *Clientset) V1Model() v1model.V1ModelInterface {
	return &fakev1model.FakeV1Model{Fake: &c.Fake}
}
