//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	common "github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/common"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostingAutoscalingPolicy) DeepCopyInto(out *HostingAutoscalingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostingAutoscalingPolicy.
func (in *HostingAutoscalingPolicy) DeepCopy() *HostingAutoscalingPolicy {
	if in == nil {
		return nil
	}
	out := new(HostingAutoscalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostingAutoscalingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostingAutoscalingPolicyList) DeepCopyInto(out *HostingAutoscalingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostingAutoscalingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostingAutoscalingPolicyList.
func (in *HostingAutoscalingPolicyList) DeepCopy() *HostingAutoscalingPolicyList {
	if in == nil {
		return nil
	}
	out := new(HostingAutoscalingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostingAutoscalingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostingAutoscalingPolicySpec) DeepCopyInto(out *HostingAutoscalingPolicySpec) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.MinCapacity != nil {
		in, out := &in.MinCapacity, &out.MinCapacity
		*out = new(int64)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = new(int64)
		**out = **in
	}
	if in.ScalableDimension != nil {
		in, out := &in.ScalableDimension, &out.ScalableDimension
		*out = new(string)
		**out = **in
	}
	if in.PolicyName != nil {
		in, out := &in.PolicyName, &out.PolicyName
		*out = new(string)
		**out = **in
	}
	if in.PolicyType != nil {
		in, out := &in.PolicyType, &out.PolicyType
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = make([]*common.AutoscalingResource, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(common.AutoscalingResource)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ServiceNamespace != nil {
		in, out := &in.ServiceNamespace, &out.ServiceNamespace
		*out = new(string)
		**out = **in
	}
	if in.SuspendedState != nil {
		in, out := &in.SuspendedState, &out.SuspendedState
		*out = new(common.HAPSuspendedState)
		(*in).DeepCopyInto(*out)
	}
	if in.SageMakerEndpoint != nil {
		in, out := &in.SageMakerEndpoint, &out.SageMakerEndpoint
		*out = new(string)
		**out = **in
	}
	if in.TargetTrackingScalingPolicyConfiguration != nil {
		in, out := &in.TargetTrackingScalingPolicyConfiguration, &out.TargetTrackingScalingPolicyConfiguration
		*out = new(common.TargetTrackingScalingPolicyConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostingAutoscalingPolicySpec.
func (in *HostingAutoscalingPolicySpec) DeepCopy() *HostingAutoscalingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(HostingAutoscalingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostingAutoscalingPolicyStatus) DeepCopyInto(out *HostingAutoscalingPolicyStatus) {
	*out = *in
	if in.ResourceIDList != nil {
		in, out := &in.ResourceIDList, &out.ResourceIDList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostingAutoscalingPolicyStatus.
func (in *HostingAutoscalingPolicyStatus) DeepCopy() *HostingAutoscalingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(HostingAutoscalingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
