/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	hyperparametertuningjob "github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/hyperparametertuningjob"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHyperparameterTuningJobs implements HyperparameterTuningJobInterface
type FakeHyperparameterTuningJobs struct {
	Fake *FakeV1Hyperparametertuningjob
	ns   string
}

var hyperparametertuningjobsResource = schema.GroupVersionResource{Group: "v1", Version: "hyperparametertuningjob", Resource: "hyperparametertuningjobs"}

var hyperparametertuningjobsKind = schema.GroupVersionKind{Group: "v1", Version: "hyperparametertuningjob", Kind: "HyperparameterTuningJob"}

// Get takes name of the hyperparameterTuningJob, and returns the corresponding hyperparameterTuningJob object, and an error if there is any.
func (c *FakeHyperparameterTuningJobs) Get(name string, options v1.GetOptions) (result *hyperparametertuningjob.HyperparameterTuningJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hyperparametertuningjobsResource, c.ns, name), &hyperparametertuningjob.HyperparameterTuningJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hyperparametertuningjob.HyperparameterTuningJob), err
}

// List takes label and field selectors, and returns the list of HyperparameterTuningJobs that match those selectors.
func (c *FakeHyperparameterTuningJobs) List(opts v1.ListOptions) (result *hyperparametertuningjob.HyperparameterTuningJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hyperparametertuningjobsResource, hyperparametertuningjobsKind, c.ns, opts), &hyperparametertuningjob.HyperparameterTuningJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hyperparametertuningjob.HyperparameterTuningJobList{ListMeta: obj.(*hyperparametertuningjob.HyperparameterTuningJobList).ListMeta}
	for _, item := range obj.(*hyperparametertuningjob.HyperparameterTuningJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hyperparameterTuningJobs.
func (c *FakeHyperparameterTuningJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hyperparametertuningjobsResource, c.ns, opts))

}

// Create takes the representation of a hyperparameterTuningJob and creates it.  Returns the server's representation of the hyperparameterTuningJob, and an error, if there is any.
func (c *FakeHyperparameterTuningJobs) Create(hyperparameterTuningJob *hyperparametertuningjob.HyperparameterTuningJob) (result *hyperparametertuningjob.HyperparameterTuningJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hyperparametertuningjobsResource, c.ns, hyperparameterTuningJob), &hyperparametertuningjob.HyperparameterTuningJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hyperparametertuningjob.HyperparameterTuningJob), err
}

// Update takes the representation of a hyperparameterTuningJob and updates it. Returns the server's representation of the hyperparameterTuningJob, and an error, if there is any.
func (c *FakeHyperparameterTuningJobs) Update(hyperparameterTuningJob *hyperparametertuningjob.HyperparameterTuningJob) (result *hyperparametertuningjob.HyperparameterTuningJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hyperparametertuningjobsResource, c.ns, hyperparameterTuningJob), &hyperparametertuningjob.HyperparameterTuningJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hyperparametertuningjob.HyperparameterTuningJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHyperparameterTuningJobs) UpdateStatus(hyperparameterTuningJob *hyperparametertuningjob.HyperparameterTuningJob) (*hyperparametertuningjob.HyperparameterTuningJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hyperparametertuningjobsResource, "status", c.ns, hyperparameterTuningJob), &hyperparametertuningjob.HyperparameterTuningJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hyperparametertuningjob.HyperparameterTuningJob), err
}

// Delete takes name of the hyperparameterTuningJob and deletes it. Returns an error if one occurs.
func (c *FakeHyperparameterTuningJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hyperparametertuningjobsResource, c.ns, name), &hyperparametertuningjob.HyperparameterTuningJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHyperparameterTuningJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hyperparametertuningjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &hyperparametertuningjob.HyperparameterTuningJobList{})
	return err
}

// Patch applies the patch and returns the patched hyperparameterTuningJob.
func (c *FakeHyperparameterTuningJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hyperparametertuningjob.HyperparameterTuningJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hyperparametertuningjobsResource, c.ns, name, pt, data, subresources...), &hyperparametertuningjob.HyperparameterTuningJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hyperparametertuningjob.HyperparameterTuningJob), err
}
