/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/aws/amazon-sagemaker-operator-for-k8s/api/hyperparametertuningjob/v1"
	scheme "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HyperparameterTuningJobsGetter has a method to return a HyperparameterTuningJobInterface.
// A group's client should implement this interface.
type HyperparameterTuningJobsGetter interface {
	HyperparameterTuningJobs(namespace string) HyperparameterTuningJobInterface
}

// HyperparameterTuningJobInterface has methods to work with HyperparameterTuningJob resources.
type HyperparameterTuningJobInterface interface {
	Create(*v1.HyperparameterTuningJob) (*v1.HyperparameterTuningJob, error)
	Update(*v1.HyperparameterTuningJob) (*v1.HyperparameterTuningJob, error)
	UpdateStatus(*v1.HyperparameterTuningJob) (*v1.HyperparameterTuningJob, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.HyperparameterTuningJob, error)
	List(opts metav1.ListOptions) (*v1.HyperparameterTuningJobList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.HyperparameterTuningJob, err error)
	HyperparameterTuningJobExpansion
}

// hyperparameterTuningJobs implements HyperparameterTuningJobInterface
type hyperparameterTuningJobs struct {
	client rest.Interface
	ns     string
}

// newHyperparameterTuningJobs returns a HyperparameterTuningJobs
func newHyperparameterTuningJobs(c *HyperparametertuningjobV1Client, namespace string) *hyperparameterTuningJobs {
	return &hyperparameterTuningJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hyperparameterTuningJob, and returns the corresponding hyperparameterTuningJob object, and an error if there is any.
func (c *hyperparameterTuningJobs) Get(name string, options metav1.GetOptions) (result *v1.HyperparameterTuningJob, err error) {
	result = &v1.HyperparameterTuningJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HyperparameterTuningJobs that match those selectors.
func (c *hyperparameterTuningJobs) List(opts metav1.ListOptions) (result *v1.HyperparameterTuningJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.HyperparameterTuningJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hyperparameterTuningJobs.
func (c *hyperparameterTuningJobs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a hyperparameterTuningJob and creates it.  Returns the server's representation of the hyperparameterTuningJob, and an error, if there is any.
func (c *hyperparameterTuningJobs) Create(hyperparameterTuningJob *v1.HyperparameterTuningJob) (result *v1.HyperparameterTuningJob, err error) {
	result = &v1.HyperparameterTuningJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		Body(hyperparameterTuningJob).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hyperparameterTuningJob and updates it. Returns the server's representation of the hyperparameterTuningJob, and an error, if there is any.
func (c *hyperparameterTuningJobs) Update(hyperparameterTuningJob *v1.HyperparameterTuningJob) (result *v1.HyperparameterTuningJob, err error) {
	result = &v1.HyperparameterTuningJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		Name(hyperparameterTuningJob.Name).
		Body(hyperparameterTuningJob).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *hyperparameterTuningJobs) UpdateStatus(hyperparameterTuningJob *v1.HyperparameterTuningJob) (result *v1.HyperparameterTuningJob, err error) {
	result = &v1.HyperparameterTuningJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		Name(hyperparameterTuningJob.Name).
		SubResource("status").
		Body(hyperparameterTuningJob).
		Do().
		Into(result)
	return
}

// Delete takes name of the hyperparameterTuningJob and deletes it. Returns an error if one occurs.
func (c *hyperparameterTuningJobs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hyperparameterTuningJobs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hyperparameterTuningJob.
func (c *hyperparameterTuningJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.HyperparameterTuningJob, err error) {
	result = &v1.HyperparameterTuningJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hyperparametertuningjobs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
