apiVersion: v1
name: amazon-sagemaker-hyperparametertuningjob
version: 1.0.0
description: A Helm chart for deploying a SageMaker HyperParameter tuning job from Kubernetes.
maintainers:
  - name: Gautam Kumar
    email: gauta@amazon.com
  - name: Suraj Kota
    email: surakota@amazon.com
  - name: Kartik Kalamadi
    email: kalamadi@amazon.com
  - name: Meghna Baijal
    email: mbaijal@amazon.com