FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl \
    wget \
    git \
    python \
    python-pip \
    vim \
    sudo \
    jq

RUN pip install awscli

# Add yq repository and install yq
RUN apt-get update && apt install -y software-properties-common && sudo add-apt-repository ppa:rmescandon/yq && apt update && apt install -y yq

# Install kubectl
RUN curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.9/2019-06-21/bin/linux/amd64/kubectl \
      && chmod +x ./kubectl && cp ./kubectl /bin

# Install eksctl
RUN curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp && mv /tmp/eksctl /bin

COPY ./codebuild/ .

CMD ["./run_canarytest.sh"]