/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package trainingjob

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	time "time"
	v1trainingjob "./api/v1/trainingjob"
	 "github.com/aws/amazon-sagemaker-operator-for-k8s//"
	internalinterfaces "github.com/aws/amazon-sagemaker-operator-for-k8s/informers/externalversions/internalinterfaces"
	trainingjob "github.com/aws/amazon-sagemaker-operator-for-k8s/listers/v1/trainingjob"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)


// TrainingJobInformer provides access to a shared informer and lister for
// TrainingJobs.
type TrainingJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() trainingjob.TrainingJobLister
}

type trainingJobInformer struct {
	factory internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace string
}

// NewTrainingJobInformer constructs a new informer for TrainingJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTrainingJobInformer(client .Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTrainingJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTrainingJobInformer constructs a new informer for TrainingJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTrainingJobInformer(client .Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.V1Trainingjob().TrainingJobs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.V1Trainingjob().TrainingJobs(namespace).Watch(context.TODO(), options)
			},
		},
		&v1trainingjob.TrainingJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *trainingJobInformer) defaultInformer(client .Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTrainingJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *trainingJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&v1trainingjob.TrainingJob{}, f.defaultInformer)
}

func (f *trainingJobInformer) Lister() trainingjob.TrainingJobLister {
	return trainingjob.NewTrainingJobLister(f.Informer().GetIndexer())
}
