/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package hostingdeployment

import (
	"time"

	hostingdeployment "github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/hostingdeployment"
	scheme "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HostingDeploymentsGetter has a method to return a HostingDeploymentInterface.
// A group's client should implement this interface.
type HostingDeploymentsGetter interface {
	HostingDeployments(namespace string) HostingDeploymentInterface
}

// HostingDeploymentInterface has methods to work with HostingDeployment resources.
type HostingDeploymentInterface interface {
	Create(*hostingdeployment.HostingDeployment) (*hostingdeployment.HostingDeployment, error)
	Update(*hostingdeployment.HostingDeployment) (*hostingdeployment.HostingDeployment, error)
	UpdateStatus(*hostingdeployment.HostingDeployment) (*hostingdeployment.HostingDeployment, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*hostingdeployment.HostingDeployment, error)
	List(opts v1.ListOptions) (*hostingdeployment.HostingDeploymentList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hostingdeployment.HostingDeployment, err error)
	HostingDeploymentExpansion
}

// hostingDeployments implements HostingDeploymentInterface
type hostingDeployments struct {
	client rest.Interface
	ns     string
}

// newHostingDeployments returns a HostingDeployments
func newHostingDeployments(c *V1HostingdeploymentClient, namespace string) *hostingDeployments {
	return &hostingDeployments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hostingDeployment, and returns the corresponding hostingDeployment object, and an error if there is any.
func (c *hostingDeployments) Get(name string, options v1.GetOptions) (result *hostingdeployment.HostingDeployment, err error) {
	result = &hostingdeployment.HostingDeployment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hostingdeployments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HostingDeployments that match those selectors.
func (c *hostingDeployments) List(opts v1.ListOptions) (result *hostingdeployment.HostingDeploymentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &hostingdeployment.HostingDeploymentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hostingdeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hostingDeployments.
func (c *hostingDeployments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hostingdeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a hostingDeployment and creates it.  Returns the server's representation of the hostingDeployment, and an error, if there is any.
func (c *hostingDeployments) Create(hostingDeployment *hostingdeployment.HostingDeployment) (result *hostingdeployment.HostingDeployment, err error) {
	result = &hostingdeployment.HostingDeployment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hostingdeployments").
		Body(hostingDeployment).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hostingDeployment and updates it. Returns the server's representation of the hostingDeployment, and an error, if there is any.
func (c *hostingDeployments) Update(hostingDeployment *hostingdeployment.HostingDeployment) (result *hostingdeployment.HostingDeployment, err error) {
	result = &hostingdeployment.HostingDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hostingdeployments").
		Name(hostingDeployment.Name).
		Body(hostingDeployment).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *hostingDeployments) UpdateStatus(hostingDeployment *hostingdeployment.HostingDeployment) (result *hostingdeployment.HostingDeployment, err error) {
	result = &hostingdeployment.HostingDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hostingdeployments").
		Name(hostingDeployment.Name).
		SubResource("status").
		Body(hostingDeployment).
		Do().
		Into(result)
	return
}

// Delete takes name of the hostingDeployment and deletes it. Returns an error if one occurs.
func (c *hostingDeployments) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hostingdeployments").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hostingDeployments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hostingdeployments").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hostingDeployment.
func (c *hostingDeployments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hostingdeployment.HostingDeployment, err error) {
	result = &hostingdeployment.HostingDeployment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hostingdeployments").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
