/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package hostingdeployment

import (
	hostingdeployment "github.com/aws/amazon-sagemaker-operator-for-k8s/api/v1/hostingdeployment"
	"github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/scheme"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
)

type V1HostingdeploymentInterface interface {
	RESTClient() rest.Interface
	HostingDeploymentsGetter
}

// V1HostingdeploymentClient is used to interact with features provided by the v1 group.
type V1HostingdeploymentClient struct {
	restClient rest.Interface
}

func (c *V1HostingdeploymentClient) HostingDeployments(namespace string) HostingDeploymentInterface {
	return newHostingDeployments(c, namespace)
}

// NewForConfig creates a new V1HostingdeploymentClient for the given config.
func NewForConfig(c *rest.Config) (*V1HostingdeploymentClient, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &V1HostingdeploymentClient{client}, nil
}

// NewForConfigOrDie creates a new V1HostingdeploymentClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *V1HostingdeploymentClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new V1HostingdeploymentClient for the given RESTClient.
func New(c rest.Interface) *V1HostingdeploymentClient {
	return &V1HostingdeploymentClient{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := hostingdeployment.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *V1HostingdeploymentClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
