/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	"fmt"

	v1batchtransformjob "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/batchtransformjob"
	v1endpointconfig "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/endpointconfig"
	v1hostingdeployment "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/hostingdeployment"
	v1hyperparametertuningjob "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/hyperparametertuningjob"
	v1model "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/model"
	v1trainingjob "github.com/aws/amazon-sagemaker-operator-for-k8s/pkg/client/clientset/versioned/typed/v1/trainingjob"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	V1Trainingjob() v1trainingjob.V1TrainingjobInterface
	V1Batchtransformjob() v1batchtransformjob.V1BatchtransformjobInterface
	V1Endpointconfig() v1endpointconfig.V1EndpointconfigInterface
	V1Hostingdeployment() v1hostingdeployment.V1HostingdeploymentInterface
	V1Hyperparametertuningjob() v1hyperparametertuningjob.V1HyperparametertuningjobInterface
	V1Model() v1model.V1ModelInterface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	v1Trainingjob             *v1trainingjob.V1TrainingjobClient
	v1Batchtransformjob       *v1batchtransformjob.V1BatchtransformjobClient
	v1Endpointconfig          *v1endpointconfig.V1EndpointconfigClient
	v1Hostingdeployment       *v1hostingdeployment.V1HostingdeploymentClient
	v1Hyperparametertuningjob *v1hyperparametertuningjob.V1HyperparametertuningjobClient
	v1Model                   *v1model.V1ModelClient
}

// V1Trainingjob retrieves the V1TrainingjobClient
func (c *Clientset) V1Trainingjob() v1trainingjob.V1TrainingjobInterface {
	return c.v1Trainingjob
}

// V1Batchtransformjob retrieves the V1BatchtransformjobClient
func (c *Clientset) V1Batchtransformjob() v1batchtransformjob.V1BatchtransformjobInterface {
	return c.v1Batchtransformjob
}

// V1Endpointconfig retrieves the V1EndpointconfigClient
func (c *Clientset) V1Endpointconfig() v1endpointconfig.V1EndpointconfigInterface {
	return c.v1Endpointconfig
}

// V1Hostingdeployment retrieves the V1HostingdeploymentClient
func (c *Clientset) V1Hostingdeployment() v1hostingdeployment.V1HostingdeploymentInterface {
	return c.v1Hostingdeployment
}

// V1Hyperparametertuningjob retrieves the V1HyperparametertuningjobClient
func (c *Clientset) V1Hyperparametertuningjob() v1hyperparametertuningjob.V1HyperparametertuningjobInterface {
	return c.v1Hyperparametertuningjob
}

// V1Model retrieves the V1ModelClient
func (c *Clientset) V1Model() v1model.V1ModelInterface {
	return c.v1Model
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		if configShallowCopy.Burst <= 0 {
			return nil, fmt.Errorf("burst is required to be greater than 0 when RateLimiter is not set and QPS is set to greater than 0")
		}
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.v1Trainingjob, err = v1trainingjob.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.v1Batchtransformjob, err = v1batchtransformjob.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.v1Endpointconfig, err = v1endpointconfig.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.v1Hostingdeployment, err = v1hostingdeployment.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.v1Hyperparametertuningjob, err = v1hyperparametertuningjob.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.v1Model, err = v1model.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.v1Trainingjob = v1trainingjob.NewForConfigOrDie(c)
	cs.v1Batchtransformjob = v1batchtransformjob.NewForConfigOrDie(c)
	cs.v1Endpointconfig = v1endpointconfig.NewForConfigOrDie(c)
	cs.v1Hostingdeployment = v1hostingdeployment.NewForConfigOrDie(c)
	cs.v1Hyperparametertuningjob = v1hyperparametertuningjob.NewForConfigOrDie(c)
	cs.v1Model = v1model.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.v1Trainingjob = v1trainingjob.New(c)
	cs.v1Batchtransformjob = v1batchtransformjob.New(c)
	cs.v1Endpointconfig = v1endpointconfig.New(c)
	cs.v1Hostingdeployment = v1hostingdeployment.New(c)
	cs.v1Hyperparametertuningjob = v1hyperparametertuningjob.New(c)
	cs.v1Model = v1model.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
