/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/aws/amazon-sagemaker-operator-for-k8s/informers/externalversions/internalinterfaces"
	trainingjob "github.com/aws/amazon-sagemaker-operator-for-k8s/informers/externalversions/v1/trainingjob"
)

// Interface provides access to each of this group's versions.
type Interface interface {
	// Trainingjob provides access to shared informers for resources in Trainingjob.
	Trainingjob() trainingjob.Interface
}

type group struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &group{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Trainingjob returns a new trainingjob.Interface.
func (g *group) Trainingjob() trainingjob.Interface {
	return trainingjob.New(g.factory, g.namespace, g.tweakListOptions)
}
